### ISSUE TITLE
关于2019年真题数据结构算法大题的一点改进建议

### ISSUE THREAD

**Issue by dekeshile** [stellarkey/912_project#1]
你好，首先很感谢你的分享。
我在看你的真题解答部分，发现了一点小小的问题，在【2019年真题数据结构算法大题】，不知你是否有注意到，具体在下面的图片里

![2019-11-21 09-13-17屏幕截图](https://user-images.githubusercontent.com/13960493/69291973-be18f100-0c3f-11ea-9fac-de69a4bb060b.png)

我的测试样例：
                1                           
           /         \                     
         2            3                   
     /          \           \               
   4            5          7             
      \         /                                
       8     6

**Comment by 73fc** [comment]
感谢童鞋的建议，已经修改，有问题共同讨论
