### ISSUE TITLE
A suggestion to the 912_project.

### ISSUE THREAD

**Issue by zmhab** [stellarkey/912_project#12]
Hello，senior schoolmates of Tsinghua University.
  I have a great honor to write this issue for you. First, let me give you a self introduction.
  I am a candidate for the post-graduate entrance examination of 2022. Now I'm preparing for the exam, and I use this repository to help my review. As we all know, GitHub **CAN NOT** be visited at all locations of Mainland of China(Because of the **GFW**...), so I suggest that you could transfer the repository to the Gitee[https://www.gitee.com](url), a Git platform that be developed by Chinese company.
  I know the action may spend lots of time, but I think we should consider it through long-term visions. First, the repository is used to help students at Mainland of China, so the way to develop it with GitHub(over the China) is not the best choice.(BaiduNetDisk needs cost some money, so it isn't a wise choice, too.)
  In addition, achieve the self-development of IT as soon as possible is a more and more important thing, so please consider this suggestion cautiously.
  Best wishes!

**Comment by stellarkey** [comment]
A great suggestion! Sorry for the delay. We will take this into consideration soon.
Summer vacation may be a good time to do some modifications.
Thanks.

**Comment by stellarkey** [comment]
https://codechina.csdn.net/A916583011/912_project_new

**Comment by zmhab** [comment]
Excellent! Sorry for delay,too. I can't use GitHub for a long time. I find that it has been a year since last update.So we can keep up to date, and told others by some ways to get more users.
