### ISSUE TITLE
关于2016年计算机组成<流水线大题>的疑问

### ISSUE THREAD

**Issue by GameOneByOne** [stellarkey/912_project#3]
你好，关于912，2016年计算机组成原理的第一道流水线大题，三个寄存器的位置摆放有点疑问，希望能请教一下，具体如下：
![image](https://user-images.githubusercontent.com/46769939/70892670-90e41680-2024-11ea-968d-cf800831d2e1.png)

按照这里的解答，让流水线时间尽可能均衡，所以寄存器放置在了A，B，D之后，但如果这样的话，
流水线的延迟（算上寄存器延迟）第二段只需要30ps，而第三段却需要60ps，也就是说第二段处理完了，第三段还在处理中，之后第二段的数据流入第三段中将会导致错误（不知道这么理解对不对），所以个人觉得这里应该是要确保三个寄存器插入之后，确保前一段的延迟不小于后一段的延迟，从而保证不会发生冲突。

所以这样的话，虽然题目不全BD的延迟不知道，但基本可以推断出，B+D=35ps，如果B延迟=30ps，D延迟=5ps的话，那么BC之间放一个，CD之间放一下，EF之间放一下，刚刚好满足要求，而且答案唯一

不知道说的对不对，请大佬指教...

**Comment by stellarkey** [comment]
有道理。考完之后或许会更新此部分。
多谢建议。

另外，关于

> 第二段处理完了，第三段还在处理中，之后第二段的数据流入第三段中将会导致错误（不知道这么理解对不对）

这个是**不准确**的，流水线的工作是根据时钟周期的上升沿和下降沿来存取数据，在同一个时钟周期内，每个流水段的数据通路相互隔绝（除非加入旁路等）。
