### ISSUE TITLE
关于2016年真题计算机网络<TCP拥塞控制大题>的疑问

### ISSUE THREAD

**Issue by GameOneByOne** [stellarkey/912_project#4]
2016年真题计算机网络<TCP拥塞控制大题>这道大题，第二问好像有些问题
![image](https://user-images.githubusercontent.com/46769939/70894558-33ea5f80-2028-11ea-87bb-d2369022a4c3.png)

当传输进行到拥塞避免的时候，应该是当前拥塞窗口的所有发送数据都收到确认后，拥塞窗口才加一，题里说阈值是16KB，则当收到ACK为16KB的报文后，拥塞窗口到达16KB，达到阈值，进入拥塞避免阶段，之后拥塞窗口的数据全部发送，要等到ACK为32KB的时候，拥塞窗口才能加一，成为17KB，而此时的ACK只到了31KB，所以拥塞窗口还是16KB，没有变。

这个是习题里的一道原题，原题里阈值是32KB，如下图：
![image](https://user-images.githubusercontent.com/46769939/70895160-63e63280-2029-11ea-812f-a02bf3ff9ca0.png)

最后，感谢分享

**Comment by stellarkey** [comment]
嗯嗯，这个没来得及改。。以习题为准。

**Comment by stellarkey** [comment]
同学你好，我认为你的答案有稍许错误，根据习题修改后的答案如下：

![Snipaste_2019-12-16_23-27-53](https://user-images.githubusercontent.com/38290992/70919369-b80a0a80-205b-11ea-857f-ba6b13c71861.png)

**Comment by yongxinruojing** [comment]
good

**Comment by yongxinruojing** [comment]
请问慢开始 每次都是2倍 怎么可能拥塞窗口是9呢，，，
