### ISSUE TITLE
关于2018年 计算机网络<路由器+TCP大题（10’）>

### ISSUE THREAD

**Issue by GameOneByOne** [stellarkey/912_project#5]
2018年 计算机网络<路由器+TCP大题（10’）>
大佬，这里没看懂，想请教一下，万分感谢！！！！
![image](https://user-images.githubusercontent.com/46769939/71089880-af8d0d80-21dc-11ea-8f9a-93ab7c69af5f.png)
题目是已知数据长度900B，TCP头20B，IP头20B，A->e1链路层头14B
这里在A->e1的过程中，数据链路层的传输，为什么是900+20+14，而不是900+20+20+14B呀，
是把TCP头还是IP头给去掉了？为什么要去掉呀？

感谢大佬指点，（要考试了，还没复习完.....）

**Comment by stellarkey** [comment]
同学你好，这里是**IP层**（网络层）分片。

> **TCP头部包含在IP层数据报的数据部分**。

IP分片需要去掉IP头部，对IP层的数据部分进行分片。

~~典例5.34是一道类似题，其是对数据链路层的**帧**进行分片，此时反而要将IP头部和TCP头部都视作帧中的数据部分。~~

**Comment by GameOneByOne** [comment]
感谢，感谢

**Comment by stellarkey** [comment]
同学你好，经过查证，典例5.34也是对IP层数据报进行分片。应该没有对帧分片的说法。
