### ISSUE TITLE
项目实在太大，能否劳烦提供其他下载方式？

### ISSUE THREAD

**Issue by chuxiuhong** [stellarkey/912_project#6]
尝试了梯子之后clone也下不下来，码云因为项目太大也没法转运，直接梯子下载zip每次都是9个G左右就失败还没有断点续传，有没有其他下载方式能下载呢？
求助

**Comment by dekeshile** [comment]
根目录下有个文件叫 【本项目其他下载方式.md】，里面有百度云的下载链接

**Comment by chuxiuhong** [comment]
> 根目录下有个文件叫 【本项目其他下载方式.md】，里面有百度云的下载链接

感谢，不过第一个百度云链接失效了，后面那个bt sync的方式也不太能用。还是很感谢

**Comment by dekeshile** [comment]
我上次存在百度云了，可以发给你

**Comment by chuxiuhong** [comment]
> 我上次存在百度云了，可以发给你

通过第二个链接存下来了，不需要麻烦你了，感谢
