### ISSUE TITLE
很多资料都失效了。。。

### ISSUE THREAD

**Issue by JaneLiu2017** [stellarkey/912_project#7]
很多资料都失效了。。。

**Comment by stellarkey** [comment]
请详细说明情况

**Comment by stellarkey** [comment]
失效盘链接已更新：https://github.com/stellarkey/912_project/commit/34625e87d361162b1584900d6bd643bf3d604ebb

**Comment by JaneLiu2017** [comment]
竟然收到回复啦~~~~感谢！！！！！










在 2020-09-08 21:25:20，"Vel" <notifications@github.com> 写道：

失效盘链接已更新：34625e8

**Comment by stellarkey** [comment]
没有其他问题的话就close了 QAQ

**Comment by JaneLiu2017** [comment]
好的，感谢！！！！
